"""
Streamlit Dashboard for Real-Time Analytics.
Connects an in-memory DuckDB engine directly to our exported Parquet file 
to visualize the clean, validated event data on the fly.
"""
import streamlit as st
import duckdb

# Configure the Streamlit page layout and metadata
st.set_page_config(page_title="User Signups Dashboard", layout="wide")

st.title("User Signups Dashboard")
st.write("Visualizing the clean output of the DuckDB data pipeline.")

# We use an in-memory DuckDB connection to query the Parquet file directly.
# This avoids needing a separate heavy database server running in the background.
try:
    conn = duckdb.connect(":memory:")

    # Define the path to the Parquet file generated by pipeline.py
    parquet_file = "data/analytics.parquet"

    # ---------------------------------------------------------
    # Metric 1: Total Validated Signups
    # ---------------------------------------------------------
    # DuckDB can run standard SQL aggregates natively over columnar Parquet files
    total_signups = conn.execute(f"SELECT COUNT(*) FROM read_parquet('{parquet_file}')").fetchone()[0]
    st.metric("Total Signups", total_signups)

    # ---------------------------------------------------------
    # Chart 1: Signups grouped by Plan Type
    # ---------------------------------------------------------
    st.subheader("Signups by Plan Type")
    # .fetchdf() converts the DuckDB query result directly into a Pandas DataFrame
    plan_df = conn.execute(
        f"SELECT plan_type, COUNT(*) as signup_count FROM read_parquet('{parquet_file}') GROUP BY plan_type ORDER BY signup_count DESC"
    ).fetchdf()
    
    # Streamlit natively renders Pandas DataFrames as interactive charts
    st.bar_chart(plan_df, x="plan_type", y="signup_count")

    # ---------------------------------------------------------
    # Table: Raw Event Feed
    # ---------------------------------------------------------
    st.subheader("Recent Signups")
    # Fetch the 100 most recent events to display in a raw data table
    recent_df = conn.execute(
        f"SELECT * FROM read_parquet('{parquet_file}') ORDER BY timestamp DESC LIMIT 100"
    ).fetchdf()
    
    # Render the DataFrame as an interactive, stretchable data table
    st.dataframe(recent_df, width="stretch")
    
except duckdb.IOException:
    # Graceful error handling if the user runs the dashboard before generating data
    st.error("Parquet file not found. Please run `python pipeline.py` first to generate the data.")
finally:
    # Always ensure the database connection is closed safely to free up memory
    if 'conn' in locals():
        conn.close()
