"""
Main ingestion and transformation pipeline.
Orchestrates reading unstructured JSON, validating schemas via Pydantic, 
and exporting clean data to Apache Parquet using DuckDB.
"""
import glob
import json
import logging
from typing import List, Dict, Any

import duckdb
import pandas as pd
from pydantic import ValidationError

from models.events import UserSignupEvent

# Configure basic logging to output severity levels and messages to the terminal
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")


def load_raw_data(file_path: str) -> List[Dict[str, Any]]:
    """
    Reads raw JSON event data from a local file.
    
    Args:
        file_path (str): The relative or absolute path to the JSON log file.
        
    Returns:
        List[Dict[str, Any]]: A list of unstructured event dictionaries directly from the JSON.
    """
    try:
        with open(file_path, "r") as file:
            return json.load(file)
    except FileNotFoundError:
        logging.error(f"Could not find {file_path}. Please check the path.")
        return []


def validate_events(raw_events: List[Dict[str, Any]]) -> List[UserSignupEvent]:
    """
    Validates raw event dictionaries against the strict Pydantic data contract.
    Isolates malformed data, preventing corrupt records from reaching downstream analytics.
    
    Args:
        raw_events (List[Dict[str, Any]]): Unstructured event payloads straight from ingestion.
        
    Returns:
        List[UserSignupEvent]: A list of strongly-typed, validated Pydantic objects.
    """
    valid_events = []
    
    for event in raw_events:
        try:
            # Pydantic enforces schema rules, type casts values, and catches missing fields
            validated_event = UserSignupEvent(**event)
            valid_events.append(validated_event)
        except ValidationError as e:
            # Log the specific validation failure without crashing the entire batch processing
            logging.warning(f"Validation failed for event {event.get('event_id', 'UNKNOWN')}: {e.errors()[0]['msg']}")
            
    return valid_events


def load_to_duckdb(events: List[UserSignupEvent], db_path: str = ":memory:") -> duckdb.DuckDBPyConnection:
    """
    Transforms validated Pydantic models into a Pandas DataFrame, then uses 
    DuckDB to natively export that DataFrame into a compressed Parquet file.
    
    Args:
        events (List[UserSignupEvent]): The clean, validated event objects.
        db_path (str): Path to the DuckDB database. Defaults to ":memory:" for ephemeral processing.
        
    Returns:
        duckdb.DuckDBPyConnection: The active database connection for subsequent querying.
    """
    conn = duckdb.connect(db_path)
    
    # Extract the raw dictionaries back out of the Pydantic models
    raw_list = [event.model_dump() for event in events]
    
    if raw_list:
        # Pandas is used here as a reliable intermediate bridge; DuckDB natively reads Pandas DataFrames
        validated_data = pd.DataFrame(raw_list) 
        
        # DuckDB directly queries the Pandas DataFrame 'validated_data' and writes the output to Parquet
        conn.execute("COPY (SELECT * FROM validated_data) TO 'data/analytics.parquet' (FORMAT PARQUET)")
        logging.info(f"Successfully exported {len(validated_data)} records to data/analytics.parquet.")
    else:
        logging.warning("No valid data to load into DuckDB.")
        
    return conn


def main() -> None:
    """
    Executes the core pipeline workflow: File Discovery -> Ingestion -> Validation -> Storage.
    """
    # Use glob to discover all matching JSON files, regardless of their dynamic timestamp
    file_paths = glob.glob("data/raw_events*.json")
    
    if not file_paths:
        logging.error("No data files found in data/ directory. Run generate_data.py first.")
        return

    logging.info("Starting data pipeline...")
    
    # 1. Ingestion: Aggregate all records from all discovered files
    raw_data = []
    for file_path in file_paths:
        raw_data.extend(load_raw_data(file_path))
    
    logging.info(f"Loaded {len(raw_data)} raw events. Starting validation...")
    
    # 2. Validation: Filter out the intentional errors generated by the faker script
    clean_events = validate_events(raw_data)
    
    logging.info("Exporting validated events to Parquet...")
    
    # 3. Storage: Push the clean data to Parquet via DuckDB
    conn = load_to_duckdb(clean_events, db_path=":memory:")
    
    # 4. Verification: Run a test analytical query directly on the newly created Parquet file
    print("\n--- Analytics Sample: Signups by Plan Type ---")
    query_result = conn.execute(
        "SELECT plan_type, COUNT(*) as signup_count FROM read_parquet('data/analytics.parquet') GROUP BY plan_type ORDER BY signup_count DESC"
    ).fetchdf()
    
    print(query_result)


if __name__ == "__main__":
    main()
